modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Double%20Doors"
logoFile="icon.png"

[[mods]]
modId="doubledoors"
version="5.1"
displayName="Double Doors"
displayURL="https://curseforge.com/minecraft/mc-mods/double-doors"
authors="Rick South"
description='''Adds the ability for identical double doors, trapdoors and fence gates to be opened simultaneously via click or pressure plates and buttons.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.doubledoors]]
    modId="collective"
    mandatory=true
    versionRange="[7.13,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.doubledoors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "doubledoors_neoforge.mixins.json"